name: Test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore:
      - main

env:
  VITE_GOOGLE_OAUTH_URL: ${{ secrets.VITE_GOOGLE_OAUTH_URL }}
  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
  VITE_JWT_TOKEN: ${{ secrets.VITE_JWT_TOKEN }}

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/composite/install-deps
      - name: Format Check
        run: yarn format:check
      - name: Linter
        run: yarn lint
      - name: Run cypress E2E tests
        run: yarn cy:run
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: cypress-coverage/lcov.info
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
